apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-deploy
  labels:
    name: deployment  
spec:
  replicas: 2
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      name: go-web-pod
      labels:
        name: deployment
    spec:
      containers:
        - name: go-web-container
          image: samir274/gowebimage:{{ .Values.image.tag }}
          ports:
          - containerPort: 7080    
